/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.payrollsystem.chart;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.CategoryAxis;
import org.jfree.chart.axis.CategoryLabelPositions;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Paul
 */
public class BarChart extends javax.swing.JPanel {

    private DefaultCategoryDataset dataset;
    private JFreeChart chart;
    private CategoryPlot categoryPlot;
    private ChartPanel chartPanel;

    /**
     * Creates new form BarChart
     */
    public BarChart() {
        initComponents();
        showBarChart();
        this.setPreferredSize(new Dimension(412, 300));
    }

    private void showBarChart() {
        dataset = new DefaultCategoryDataset();

        dataset.addValue(4, "NON-MWE", "NON-MWE");

        dataset.addValue(3, "MWE", "MWE");

        chart = ChartFactory.createBarChart("", "Categories", "Values", dataset, PlotOrientation.VERTICAL, true, true, false);

        categoryPlot = chart.getCategoryPlot();
        categoryPlot.setBackgroundPaint(new Color(255, 255, 255));

        // Enable grid lines on the range axis (Y-axis)
        categoryPlot.setRangeGridlinesVisible(true);
        categoryPlot.setRangeGridlinePaint(Color.GRAY);

        // Customize the Y-axis to show integer values
        NumberAxis rangeAxis = (NumberAxis) categoryPlot.getRangeAxis();
        rangeAxis.setStandardTickUnits(NumberAxis.createIntegerTickUnits());

        // Center the category labels beneath the bars
        CategoryAxis domainAxis = categoryPlot.getDomainAxis();
        domainAxis.setCategoryLabelPositions(CategoryLabelPositions.STANDARD);

        chartPanel = new ChartPanel(chart);
        this.removeAll();
        this.add(chartPanel, BorderLayout.CENTER);
        this.validate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this
     * code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
