/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.payrollsystem.modals;

import com.mycompany.payrollsystem.Util;
import java.awt.Color;

/**
 *
 * @author Paul
 */
public class CreatePayrollModal extends javax.swing.JFrame {

    private final Util util;
    
    /**
     * Creates new form CreatePayroll
     */
    public CreatePayrollModal() {
        this.util = new Util();
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        setLocationRelativeTo(null);
        util.fitImageToComponent(sss_icon_label, "images/sss-removebg-preview.png");
        util.fitImageToComponent(philhealth_icon_label, "images/philHealth-removebg-preview.png");
        util.fitImageToComponent(pag_ibig_icon_label, "images/pag-ibig-removebg-preview.png");
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this
     * code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        roundedCornersPanel1 = new com.mycompany.payrollsystem.swing.RoundedCornersPanel();
        modal_title2 = new javax.swing.JLabel();
        close_icon_modal2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        backgroundLabelCode = new com.mycompany.payrollsystem.swing.BackgroundLabel();
        jTextField5 = new javax.swing.JTextField();
        backgroundLabelName = new com.mycompany.payrollsystem.swing.BackgroundLabel();
        jTextField6 = new javax.swing.JTextField();
        backgroundLabelPayrollMonth = new com.mycompany.payrollsystem.swing.BackgroundLabel();
        jComboBox9 = new javax.swing.JComboBox<>();
        jComboBox10 = new javax.swing.JComboBox<>();
        backgroundLabelDateStart = new com.mycompany.payrollsystem.swing.BackgroundLabel();
        jTextField7 = new javax.swing.JTextField();
        backgroundLabelDateEnd = new com.mycompany.payrollsystem.swing.BackgroundLabel();
        jTextField8 = new javax.swing.JTextField();
        backgroundLabelProcessType = new com.mycompany.payrollsystem.swing.BackgroundLabel();
        jComboBox11 = new javax.swing.JComboBox<>();
        backgroundLabelProcessType1 = new com.mycompany.payrollsystem.swing.BackgroundLabel();
        jComboBox12 = new javax.swing.JComboBox<>();
        backgroundLabelProcessType2 = new com.mycompany.payrollsystem.swing.BackgroundLabel();
        jComboBox13 = new javax.swing.JComboBox<>();
        backgroundLabelProcessType3 = new com.mycompany.payrollsystem.swing.BackgroundLabel();
        jTextField9 = new javax.swing.JTextField();
        backgroundLabelProcessType4 = new com.mycompany.payrollsystem.swing.BackgroundLabel();
        jTextField10 = new javax.swing.JTextField();
        backgroundLabelProcessType5 = new com.mycompany.payrollsystem.swing.BackgroundLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        philhealth_icon_label = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        sss_icon_label = new javax.swing.JLabel();
        jCheckBox3 = new javax.swing.JCheckBox();
        pag_ibig_icon_label = new javax.swing.JLabel();
        save_changes_modal_button2 = new javax.swing.JButton();
        close_modal_button2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        roundedCornersPanel1.setBackground(new java.awt.Color(245, 247, 248));

        modal_title2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        modal_title2.setForeground(new java.awt.Color(51, 51, 51));
        modal_title2.setText("Payroll Details");

        close_icon_modal2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close_icon_modal2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/payrollsystem/icons/x-icon.png"))); // NOI18N
        close_icon_modal2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                close_icon_modal2MousePressed(evt);
            }
        });

        backgroundLabelCode.setBackground(new java.awt.Color(0, 158, 251));
        backgroundLabelCode.setLabelText("Code");

        jTextField5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(153, 153, 153));
        jTextField5.setText("Payroll Code");
        jTextField5.setMargin(new java.awt.Insets(2, 10, 2, 2));

        backgroundLabelName.setBackground(new java.awt.Color(0, 158, 251));
        backgroundLabelName.setLabelText("Name");

        jTextField6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(153, 153, 153));
        jTextField6.setText("Payroll Name");
        jTextField6.setMargin(new java.awt.Insets(2, 10, 2, 2));

        backgroundLabelPayrollMonth.setBackground(new java.awt.Color(0, 158, 251));
        backgroundLabelPayrollMonth.setLabelText("Payroll Month");

        jComboBox9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox9.setForeground(new java.awt.Color(102, 102, 102));
        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June ", "July", "August", "September", "October", "November", "December", " " }));

        jComboBox10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox10.setForeground(new java.awt.Color(102, 102, 102));
        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", "2041" }));

        backgroundLabelDateStart.setBackground(new java.awt.Color(0, 158, 251));
        backgroundLabelDateStart.setLabelText("Date Start");

        jTextField7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(153, 153, 153));
        jTextField7.setText("2024-08-01");
        jTextField7.setMargin(new java.awt.Insets(2, 10, 2, 2));

        backgroundLabelDateEnd.setBackground(new java.awt.Color(0, 158, 251));
        backgroundLabelDateEnd.setLabelText("Date End");

        jTextField8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(153, 153, 153));
        jTextField8.setText("2024-08-27");
        jTextField8.setMargin(new java.awt.Insets(2, 10, 2, 2));

        backgroundLabelProcessType.setBackground(new java.awt.Color(0, 158, 251));
        backgroundLabelProcessType.setLabelText("Process Type");

        jComboBox11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox11.setForeground(new java.awt.Color(102, 102, 102));
        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "REGULAR PAYROLL", "13TH MONTH PAYROLL", "BONUS PAYROLL", "SPECIAL PAYROLL", " " }));

        backgroundLabelProcessType1.setBackground(new java.awt.Color(0, 158, 251));
        backgroundLabelProcessType1.setLabelText("Payroll Type");

        jComboBox12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox12.setForeground(new java.awt.Color(102, 102, 102));
        jComboBox12.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Weekly", "Semi - Monthly", "Monthly", " " }));

        backgroundLabelProcessType2.setBackground(new java.awt.Color(0, 158, 251));
        backgroundLabelProcessType2.setLabelText("Type Info");

        jComboBox13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox13.setForeground(new java.awt.Color(102, 102, 102));
        jComboBox13.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "First Half", "Second Half", " " }));

        backgroundLabelProcessType3.setBackground(new java.awt.Color(0, 158, 251));
        backgroundLabelProcessType3.setLabelText("Other Income Included");

        jTextField9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(153, 153, 153));
        jTextField9.setMargin(new java.awt.Insets(2, 10, 2, 2));

        backgroundLabelProcessType4.setBackground(new java.awt.Color(0, 158, 251));
        backgroundLabelProcessType4.setLabelText("Loan Included");

        jTextField10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField10.setForeground(new java.awt.Color(153, 153, 153));
        jTextField10.setMargin(new java.awt.Insets(2, 10, 2, 2));

        backgroundLabelProcessType5.setBackground(new java.awt.Color(0, 158, 251));
        backgroundLabelProcessType5.setLabelText("Statutory");

        jCheckBox1.setBackground(new java.awt.Color(245, 247, 248));
        buttonGroup2.add(jCheckBox1);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        philhealth_icon_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jCheckBox2.setBackground(new java.awt.Color(245, 247, 248));
        buttonGroup2.add(jCheckBox2);

        sss_icon_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jCheckBox3.setBackground(new java.awt.Color(245, 247, 248));
        buttonGroup2.add(jCheckBox3);

        pag_ibig_icon_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        save_changes_modal_button2.setBackground(new java.awt.Color(0, 204, 51));
        save_changes_modal_button2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        save_changes_modal_button2.setForeground(new java.awt.Color(255, 255, 255));
        save_changes_modal_button2.setText("Save Changes");

        close_modal_button2.setBackground(new java.awt.Color(204, 0, 0));
        close_modal_button2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        close_modal_button2.setForeground(new java.awt.Color(255, 255, 255));
        close_modal_button2.setText("Close");
        close_modal_button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_modal_button2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roundedCornersPanel1Layout = new javax.swing.GroupLayout(roundedCornersPanel1);
        roundedCornersPanel1.setLayout(roundedCornersPanel1Layout);
        roundedCornersPanel1Layout.setHorizontalGroup(
            roundedCornersPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addGroup(roundedCornersPanel1Layout.createSequentialGroup()
                .addGroup(roundedCornersPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundedCornersPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(modal_title2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(close_icon_modal2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roundedCornersPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(roundedCornersPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(backgroundLabelCode, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backgroundLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backgroundLabelPayrollMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backgroundLabelDateStart, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backgroundLabelDateEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backgroundLabelProcessType, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backgroundLabelProcessType1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backgroundLabelProcessType2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backgroundLabelProcessType3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backgroundLabelProcessType4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backgroundLabelProcessType5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(roundedCornersPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(roundedCornersPanel1Layout.createSequentialGroup()
                                .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(roundedCornersPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jComboBox11, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                                .addComponent(jComboBox12, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox13, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(roundedCornersPanel1Layout.createSequentialGroup()
                                .addComponent(jCheckBox1)
                                .addGap(12, 12, 12)
                                .addComponent(sss_icon_label, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(jCheckBox2)
                                .addGap(18, 18, 18)
                                .addComponent(philhealth_icon_label, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(jCheckBox3)
                                .addGap(18, 18, 18)
                                .addComponent(pag_ibig_icon_label, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 142, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedCornersPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(close_modal_button2)
                        .addGap(10, 10, 10)
                        .addComponent(save_changes_modal_button2)))
                .addGap(15, 15, 15))
        );
        roundedCornersPanel1Layout.setVerticalGroup(
            roundedCornersPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedCornersPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(roundedCornersPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(close_icon_modal2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modal_title2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(roundedCornersPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundedCornersPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addGroup(roundedCornersPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backgroundLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(backgroundLabelCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(roundedCornersPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundedCornersPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(backgroundLabelPayrollMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundedCornersPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backgroundLabelDateStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundedCornersPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backgroundLabelDateEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundedCornersPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundedCornersPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBox11, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox12, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roundedCornersPanel1Layout.createSequentialGroup()
                        .addComponent(backgroundLabelProcessType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(backgroundLabelProcessType1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundedCornersPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backgroundLabelProcessType2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox13, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(roundedCornersPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backgroundLabelProcessType3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundedCornersPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backgroundLabelProcessType4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundedCornersPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundedCornersPanel1Layout.createSequentialGroup()
                        .addGroup(roundedCornersPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pag_ibig_icon_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(roundedCornersPanel1Layout.createSequentialGroup()
                                .addGroup(roundedCornersPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sss_icon_label, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(philhealth_icon_label, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCheckBox1)
                                    .addComponent(jCheckBox2))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(12, 12, 12)
                        .addGroup(roundedCornersPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(close_modal_button2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(save_changes_modal_button2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(110, 110, 110))
                    .addGroup(roundedCornersPanel1Layout.createSequentialGroup()
                        .addGroup(roundedCornersPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox3)
                            .addComponent(backgroundLabelProcessType5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundedCornersPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(roundedCornersPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void close_icon_modal2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_icon_modal2MousePressed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_close_icon_modal2MousePressed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void close_modal_button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_modal_button2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_close_modal_button2ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(CreatePayrollModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(CreatePayrollModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(CreatePayrollModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(CreatePayrollModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new CreatePayrollModal().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.payrollsystem.swing.BackgroundLabel backgroundLabelCode;
    private com.mycompany.payrollsystem.swing.BackgroundLabel backgroundLabelDateEnd;
    private com.mycompany.payrollsystem.swing.BackgroundLabel backgroundLabelDateStart;
    private com.mycompany.payrollsystem.swing.BackgroundLabel backgroundLabelName;
    private com.mycompany.payrollsystem.swing.BackgroundLabel backgroundLabelPayrollMonth;
    private com.mycompany.payrollsystem.swing.BackgroundLabel backgroundLabelProcessType;
    private com.mycompany.payrollsystem.swing.BackgroundLabel backgroundLabelProcessType1;
    private com.mycompany.payrollsystem.swing.BackgroundLabel backgroundLabelProcessType2;
    private com.mycompany.payrollsystem.swing.BackgroundLabel backgroundLabelProcessType3;
    private com.mycompany.payrollsystem.swing.BackgroundLabel backgroundLabelProcessType4;
    private com.mycompany.payrollsystem.swing.BackgroundLabel backgroundLabelProcessType5;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel close_icon_modal2;
    private javax.swing.JButton close_modal_button2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox11;
    private javax.swing.JComboBox<String> jComboBox12;
    private javax.swing.JComboBox<String> jComboBox13;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel modal_title2;
    private javax.swing.JLabel pag_ibig_icon_label;
    private javax.swing.JLabel philhealth_icon_label;
    private com.mycompany.payrollsystem.swing.RoundedCornersPanel roundedCornersPanel1;
    private javax.swing.JButton save_changes_modal_button2;
    private javax.swing.JLabel sss_icon_label;
    // End of variables declaration//GEN-END:variables
}
