/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.payrollsystem.swing;

import com.mycompany.payrollsystem.Util;
import com.mycompany.payrollsystem.model.MenuModel;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

/**
 *
 * @author Paul
 */
public class MenuItem extends javax.swing.JPanel {

    /**
     * @param selected the selected to set
     */
    public void setSelected(boolean selected) {
        this.selected = selected;
        repaint();
    }

    public void setOver(boolean over) {
        this.over = over;
        repaint();
    }

    /**
     * Creates new form MenuItem
     */
    private boolean selected;
    private boolean over;
    private final Util util = new Util();
    private final Color leftBorderColor = new Color(255, 255, 255);
    private final int ICON_WIDTH = 25;
    private final int ICON_HEIGHT = 25;

    public MenuItem() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this
     * code. The content of this method is always regenerated by the Form Editor.
     *
     * @param obj
     */
    public void setItem(Object obj) {
        if (obj instanceof MenuModel item) {
            icon_label.setIcon(item.toIcon(ICON_WIDTH, ICON_HEIGHT));
            name_label.setText(item.getName());
        }
    }

    @Override
    protected void paintComponent(Graphics graphics) {

        if (selected || over) {
            Graphics2D g2 = (Graphics2D) graphics;
            g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

            if (selected) {
                setBackground(new Color(47, 71, 186));
                name_label.setForeground(new Color(255, 255, 255));
                util.setLeftBorder(border_label, leftBorderColor);
            } else {
                setBackground(new Color(66, 194, 255));
                name_label.setForeground(new Color(255, 255, 255));

            }

            g2.fillRect(0, 0, getWidth(), getHeight());

            super.paintComponent(graphics);
        }

    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        border_label = new javax.swing.JLabel();
        roundedPanel1 = new com.mycompany.payrollsystem.swing.RoundedCornersPanel();
        icon_label = new javax.swing.JLabel();
        name_label = new javax.swing.JLabel();

        roundedPanel1.setBackground(new java.awt.Color(203, 209, 238));

        javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(icon_label, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        roundedPanel1Layout.setVerticalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(icon_label, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addGap(8, 8, 8))
        );

        name_label.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        name_label.setForeground(new java.awt.Color(102, 102, 102));
        name_label.setText("Dashboard");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(border_label, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(roundedPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(name_label, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roundedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(border_label, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(name_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel border_label;
    private javax.swing.JLabel icon_label;
    private javax.swing.JLabel name_label;
    private com.mycompany.payrollsystem.swing.RoundedCornersPanel roundedPanel1;
    // End of variables declaration//GEN-END:variables
}
