/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.payrollsystem.cell;

/**
 *
 * @author Paul
 */
public class PanelStatus extends javax.swing.JPanel {

    /**
     * Creates new form PanelStatus
     */
    public PanelStatus() {
        initComponents();
    }
    
    public void setStatus(String status) {
        statusText.setText(status);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this
     * code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundedCornersPanel2 = new com.mycompany.payrollsystem.swing.RoundedCornersPanel();
        statusText = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));

        roundedCornersPanel2.setBackground(new java.awt.Color(51, 204, 0));
        roundedCornersPanel2.setPreferredSize(new java.awt.Dimension(80, 30));

        statusText.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        statusText.setForeground(new java.awt.Color(255, 255, 255));
        statusText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statusText.setText("Active");

        javax.swing.GroupLayout roundedCornersPanel2Layout = new javax.swing.GroupLayout(roundedCornersPanel2);
        roundedCornersPanel2.setLayout(roundedCornersPanel2Layout);
        roundedCornersPanel2Layout.setHorizontalGroup(
            roundedCornersPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedCornersPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusText, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addContainerGap())
        );
        roundedCornersPanel2Layout.setVerticalGroup(
            roundedCornersPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusText, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(roundedCornersPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundedCornersPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.payrollsystem.swing.RoundedCornersPanel roundedCornersPanel2;
    private javax.swing.JLabel statusText;
    // End of variables declaration//GEN-END:variables
}
