/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.payrollsystem.cell;

import java.awt.Color;

/**
 *
 * @author Paul
 */
public class PanelActionButtons extends javax.swing.JPanel {

    /**
     * Creates new form PanelActionButtons
     */
    public PanelActionButtons() {
        initComponents();
        setOpaque(false);
           
        income_button.setDefaultColor(new Color(0,204,51));
        deduction_button.setDefaultColor(new Color(204,0,0));
        remove_button.setDefaultColor(new Color(233, 171, 46));
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this
     * code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        deduction_button = new com.mycompany.payrollsystem.cell.ActionButton();
        remove_button = new com.mycompany.payrollsystem.cell.ActionButton();
        income_button = new com.mycompany.payrollsystem.cell.ActionButton();

        setLayout(new java.awt.GridBagLayout());

        deduction_button.setForeground(new java.awt.Color(255, 255, 255));
        deduction_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/payrollsystem/icons/circular_minus_icon_small.png"))); // NOI18N
        deduction_button.setText("Deduction");
        deduction_button.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        deduction_button.setPreferredSize(new java.awt.Dimension(75, 30));
        deduction_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deduction_buttonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 33;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 7, 0, 0);
        add(deduction_button, gridBagConstraints);

        remove_button.setForeground(new java.awt.Color(255, 255, 255));
        remove_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/payrollsystem/icons/circular_close_icon_black_small.png"))); // NOI18N
        remove_button.setText("REMOVE");
        remove_button.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        remove_button.setPreferredSize(new java.awt.Dimension(70, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 35;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 7, 0, 0);
        add(remove_button, gridBagConstraints);

        income_button.setForeground(new java.awt.Color(255, 255, 255));
        income_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/payrollsystem/icons/circular_plus_icon_small.png"))); // NOI18N
        income_button.setText("Income");
        income_button.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        income_button.setPreferredSize(new java.awt.Dimension(70, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 39;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(income_button, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void deduction_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deduction_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deduction_buttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.payrollsystem.cell.ActionButton deduction_button;
    private com.mycompany.payrollsystem.cell.ActionButton income_button;
    private com.mycompany.payrollsystem.cell.ActionButton remove_button;
    // End of variables declaration//GEN-END:variables
}
