/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.payrollsystem.cell;

import com.mycompany.payrollsystem.event.TableEditActionEvent;
import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.event.ActionEvent;

/**
 *
 * @author Paul
 */
public class UserManagementPanelAction extends javax.swing.JPanel {

    /**
     * Creates new form UserManagementPanelAction
     */
    public UserManagementPanelAction() {
        initComponents();
        
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 0;
        gbc.weighty = 0;
        gbc.fill = GridBagConstraints.NONE;
        
        add(edit_credentials_button, gbc);
        
        edit_credentials_button.setButtonPressedColor(new Color(0, 111, 176));
        edit_credentials_button.setDefaultColor(new Color(0, 158, 251));
    }

    public void initEvent(TableEditActionEvent event, int row) {
        edit_credentials_button.addActionListener((ActionEvent e) -> {
            event.onEdit(row);
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this
     * code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        edit_credentials_button = new com.mycompany.payrollsystem.cell.ActionButton();

        setLayout(new java.awt.GridBagLayout());

        edit_credentials_button.setForeground(new java.awt.Color(255, 255, 255));
        edit_credentials_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/payrollsystem/icons/edit_profile.png"))); // NOI18N
        edit_credentials_button.setText("Change Credential");
        edit_credentials_button.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(edit_credentials_button, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.payrollsystem.cell.ActionButton edit_credentials_button;
    // End of variables declaration//GEN-END:variables
}
