/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.payrollsystem.component;

import com.mycompany.payrollsystem.model.CardModel;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

/**
 *
 * @author Paul
 */
public class Card extends javax.swing.JPanel {

    
    
    private final int ARC_WIDTH = 15;
    private final int ARC_HEIGHT = 15;
    private final int ICON_WIDTH = 20;
    private final int ICON_HEIGHT = 20;
    
    // Column 1 card color -> [47,71,186]
    // Column 2 card color -> [255,141,7]
    // Column 3 card color -> [220,53,69]
    
    /**
     * Creates new form NewJPanel
     */
     
    public Card() {
        initComponents();
        setOpaque(false);
    }
    
    public void setupData(CardModel cardModel) {
//        card_name.setText(cardModel.getCardText());
//        count.setText(cardModel.getCount().toString());
//        logo_panel.setIcon(cardModel.toIcon(ICON_WIDTH, ICON_HEIGHT));
    }
    
    
    @Override
    protected void paintComponent(Graphics graphics) {
        Graphics2D g2 = (Graphics2D) graphics;
        g2.setColor(getBackground());
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), ARC_WIDTH, ARC_HEIGHT);
        super.paintComponent(graphics);
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this
     * code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 167, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.payrollsystem.swing.RoundedPanel roundedPanel2;
    private com.mycompany.payrollsystem.swing.RoundedPanel roundedPanel3;
    // End of variables declaration//GEN-END:variables
}
